### ISSUE TITLE
Sensitivity of HCLA model to tissue of origin

### ISSUE THREAD

**Issue by SirKuikka** [LungCellAtlas/HLCA#12]
Hi,

Would you expect your method to be quite sensitive to the tissue of origin? I have been using HCLA, but the query cells are not quite 100% lung tissue-resident cells. For example, I tested this PBMC dataset and the cells form their own clusters in UMAP. Is this an expected result?

![image](https://github.com/LungCellAtlas/HLCA/assets/6902136/342f6c50-d87a-4c8a-98fb-fb90c718024f)

**Comment by LisaSikkema** [comment]
Hi @SirKuikka ,

Interesting to hear that you're combining the HLCA with PBMCs! I haven't tried it myself, but it doesn't surprise me a lot that they're not mixing well. I would expect though that cells of the same type from lung and blood are close together, even if not mixing.

It could also be that there are other issues with the data, then I would have to know a bit more about how the data was generated etc. 

Maybe you could also take a look at other datasets that include both blood and lung (or blood and other organs), e.g. the tabula sapiens, and see how well cells from blood and other organs integrated in those cases?

**Comment by SirKuikka** [comment]
I have lung cancer cells and immune cells (PBMCs and some tumor-stimulated ones), and I see this same phenomenom, I.e., query and reference cells are not mixing. If the immune cells would have at least mixed,  it would have given some reason to believe that the tumor cells are indeed tumor cells, and not just epithelial cells. Sorry for explaining it poorly. 

But this visualization was just for PBMCs. I wonder if real tissue resident T cells from healthy tissue would at least produce the desired mixing effect. I will have to test.

**Comment by SirKuikka** [comment]
So I guess I'm just trying to speculate why the method is working the way it does. Because I'm not using whole lung tissue or because my cells are just different from the reference cells.

**Comment by LisaSikkema** [comment]
Okay I'm not sure if I understand correctly: you mapped both PBMCs, and cells from a lung tumor sample? Are these all cells from the tumor, or just the immune? Or just the cancer cells?
Aside from the cancer cells, I would expect cells from a tumor sample to largely mix with the reference (as they also do in the lung cancer mapping example in the paper).

**Comment by SirKuikka** [comment]
I have epithelial cells, which are the tumor cells (presumably) and then T cells, B cells and monocytes. The immune cells are PBMCs. 

![rplot65](https://github.com/LungCellAtlas/HLCA/assets/6902136/9f71aa56-a386-4f5c-a052-1f45dba602a5)


![rplot59](https://github.com/LungCellAtlas/HLCA/assets/6902136/72f5fa23-def9-4f96-aa04-8e3a9e05bbea)

**Comment by SirKuikka** [comment]
I'm like trying to use HCLA to show that the tumor cells are different from normal healthy epithelial cells. But it's quite  difficult when they cluster like this.

**Comment by LisaSikkema** [comment]
Yes you would ideally need a better control, cells of which you know for sure they should mix with the HLCA. Do you not have any other cells from the tumor?

**Comment by SirKuikka** [comment]
Unfortunately not. I have only these. But thanks for all your help again. I'm closing this issue. 🐱
