### ISSUE TITLE
how is the CO annotation generated?

### ISSUE THREAD

**Issue by YOU-k** [LungCellAtlas/HLCA#13]
Thanks for providing such a useful resource summarizing expression profiles from lungs. 
I checked the labels provided on cellxgene, there are several sets of labels. I understand how the author provided labels are generated according to the method section in the paper. but how are the CO labels  in the standard categories generated? I noticed there can be inconsistency between any level of the annotation compared to it. 
Cheers,
Yue

**Comment by LisaSikkema** [comment]
Hi Yue,

Thank you for your kind words! You can find the exact mapping we used to go from the final annotations to the cell-ontology-based ones in the reproducibility GitHub, here: https://github.com/LungCellAtlas/HLCA_reproducibility/blob/main/supporting_files/metadata_harmonization/cell_type_mapping_to_cellontology.csv
Let me know if that answers your question or if you need anything else!

**Comment by YOU-k** [comment]
Thanks, Lisa, that's very helpful.
