### ISSUE TITLE
Myer_2021, Meyer_Nikolic_2022 extension publications

### ISSUE THREAD

**Issue by flde** [LungCellAtlas/HLCA#16]
Dear HLCA Team,

Thank you for your excellent work! I have subset the HLCA and manually added metadata. However, I am encountering difficulties in locating the publications for study IDs Meyer_2021 and Meyer_Nikolic_2022. Both involve healthy patients from the extended dataset.

My initial assumption was that these studies might be associated with HCLA reference [70](https://www.nature.com/articles/s41586-021-04345-x#Sec15) published in 2021. Nevertheless, the cell IDs for both studies in HLCA include the "_unpubl" prefix, which suggests they may not be linked to reference 70.

I am seeking further information on these studies to determine the collection methods used, whether by bronchoscopic lung cryobiopsy (BCL), bronchoalveolar lavage (BAL), tissue sections from donor lungs, or brushings. Given that these are samples from healthy lungs, the latter two methods are more likely.

I would greatly appreciate any help in retrieving this information. Please let me know if I have overlooked any details, and thank you again for providing such a valuable resource.

Best wishes,
Florian

**Comment by flde** [comment]
Great, I finally managed to identify the 'tissue_sampling_method' column. I apologize for overlooking it earlier. However, if you still have information about the studies, I would greatly appreciate your help. Especially which tissue_dissociation_protocol was used for Meyer_2021.

**Comment by LisaSikkema** [comment]
Hey Florian, thank you for your message! Seems like you figured it out more or less. You can find the publication information with each study in supplementary table 1 (column P, Q and R). The _unpubl suffixes are a bit outdated, we got those datasets initially before they were published but by the time our atlas came out those datasets had been published too. You should be able to find the tissue dissociation protocols in the papers :) let me know if you need any more information!

**Comment by flde** [comment]
Hello Lisa, 

many thanks for your input and time that is highly appreciated. I could resolve my uncertainties and filled in the missing meta data. The detailed annotation about the library preparation is such a valuable insight. 

As you have shown in the publication, the digestion chemistry and time has a strong impact on the transcriptome signature. As I understand it, due to the digestion cells are likely to release cytokines and other signaling molecules that induce a stress response. 

I think technical alteration by the digestion protocol are fundamental different to other technical variability. For example, the choice of 10x chemistry determines the feature sampling space and the feature specific sampling efficiency. However, I think this variation is to some extend quantifiable and can be captured as a function of the total number of UMI per cell. The digestion protocol on the other hand does alter the biological cell state. I do believe that this is not quantifiable at all and I become increasingly worried that it is a major limitation when comparing scRNA-seq data between studies. 

Again, many thanks! 
Best, Florian
