### ISSUE TITLE
HLCA-core Seurat Object normalised counts

### ISSUE THREAD

**Issue by carissaynchen** [LungCellAtlas/HLCA#9]
Hello,

I downloaded the seurat object from cellxgene but I can't find the normalised counts in scale.data nor assays slot, and I can only find the raw counts. Is it only available in the adata object?

**Comment by LisaSikkema** [comment]
Hi @carissaynchen ,

I haven't worked with the Seurat Object myself (it was automatically generated by cellxgene), but would this page be of help?
https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/seurat_encoding.md

If not, I can check with the cellxgene people

**Comment by carissaynchen** [comment]
Ah, it's there, thank you!
